### ISSUE TITLE
Avoid mixing async/await and callbacks 

### ISSUE THREAD

**Issue by follywolly** [Mennauu/pt-team-19-20#10]
## Issue location
https://github.com/Mennauu/pt-team-19-20/blob/f788c331c979fe1925c252f058f257d46e6e13f1/server/routes/get/profile.js#L9-L13

## Issue description
Avoid mixing async/await and callbacks since it decreases scanability and increases complexity of your code. Use either one pattern or the other.
Catch errors thrown by a failed await with `try {} catch (e) {}`. I'd say it's not really necessary here since mongoose will only throw an error if you provide invalid parameters or connection to the db is lost.

## How to solve
(reminder, this is an example of what you can do, not a set rule)

### Before
```js
await User.findOne({ _id: id, username: username }, async (err, results) => { 
  if (err) return res.redirect('back') 
  
  if (results) { 
    console.log(req.user.matched)
     // ... rest
```
### After

With error check:
```js
let user;
try {
  user = await User.findOne({ _id: id, username: username })
} catch (e) {
  res.redirect('back')
  return
}

if (user) { // maybe find a way to make this a short if (!user) check for early return
  console.log(req.user.matched)
  // ... rest
```

Without error check: (make sure id and username are expected value types (in this case both strings I think) and nothing else)
```js
const user = await User.findOne({ _id: id, username: username })

if (user) {
  console.log(req.user.matched)
  // ... rest
```

## Benefits
- Improved readability
- More consistent code

## Disclaimer

Please think about every opened issue and decide wether or not you want to do anything with it. It's not important to do it my way, it's important to _be able to explain what you did or didn't do with it and why_.

**Comment by chelseadoeleman** [comment]
Thanks!
